# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBMIProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_height_ft', models.IntegerField(help_text='Enter height in feet')),
                ('human_height_in', models.IntegerField(help_text='Enter height in inches')),
            ],
        ),
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_weight', models.FloatField(help_text='Enter weight in pounds')),
                ('weight_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userbmiprofile',
            name='human_weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.models.UserProfile'),
        ),
    ]
