# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20161020_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbmiprofile',
            old_name='human_weight',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
