# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20161020_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbmiprofile',
            old_name='human_height_ft',
            new_name='Feet',
        ),
        migrations.RenameField(
            model_name='userbmiprofile',
            old_name='human_height_in',
            new_name='Inches',
        ),
        migrations.RemoveField(
            model_name='userbmiprofile',
            name='weight',
        ),
        migrations.AddField(
            model_name='userbmiprofile',
            name='Weight',
            field=models.FloatField(default=150, help_text='Enter weight in pounds'),
            preserve_default=False,
        ),
    ]
