# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20161022_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbmiprofile',
            old_name='Feet',
            new_name='Height',
        ),
        migrations.RemoveField(
            model_name='userbmiprofile',
            name='Weight',
        ),
        migrations.AddField(
            model_name='userbmiprofile',
            name='weight',
            field=models.ForeignKey(default=150, on_delete=django.db.models.deletion.CASCADE, to='fitness.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_weight',
            field=models.FloatField(default='150', help_text='Enter weight in pounds'),
        ),
    ]
