# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_auto_20161022_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbmiprofile',
            name='Weight',
            field=models.IntegerField(default=150, help_text='Enter weight in pounds'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_weight',
            field=models.IntegerField(default=150, help_text='Enter weight in pounds'),
        ),
    ]
