# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_auto_20161022_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbmiprofile',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='userbmiprofile',
            name='Inches',
        ),
        migrations.RemoveField(
            model_name='userbmiprofile',
            name='Weight',
        ),
        migrations.AddField(
            model_name='userbmiprofile',
            name='human_height_ft',
            field=models.IntegerField(default=1, help_text='Enter height in feet', verbose_name='Height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbmiprofile',
            name='human_height_in',
            field=models.IntegerField(default=1, help_text='Enter height in inches', verbose_name='Inches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbmiprofile',
            name='weight',
            field=models.IntegerField(default=150, help_text='Enter weight in pounds', verbose_name='Weight'),
        ),
    ]
