# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_auto_20161022_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbmiprofile',
            name='human_height_ft',
        ),
        migrations.RemoveField(
            model_name='userbmiprofile',
            name='human_height_in',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_weight',
        ),
        migrations.AddField(
            model_name='userbmiprofile',
            name='height',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='fitness.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_height_ft',
            field=models.IntegerField(default=1, help_text='Enter height in feet', verbose_name='Height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_height_in',
            field=models.IntegerField(default=1, help_text='Enter height in inches', verbose_name='Inches'),
            preserve_default=False,
        ),
    ]
