# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_auto_20161022_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbmiprofile',
            name='height',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_height_ft',
        ),
        migrations.AddField(
            model_name='userbmiprofile',
            name='human_height_ft',
            field=models.IntegerField(default=5, help_text='Enter height in feet', verbose_name='Height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbmiprofile',
            name='human_height_in',
            field=models.IntegerField(default=10, help_text='Enter height in inches', verbose_name='Inches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_weight',
            field=models.IntegerField(default=150, help_text='Enter weight in pounds'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_weight_ft',
            field=models.IntegerField(default=5, verbose_name='Feet'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_height_in',
            field=models.IntegerField(default=10, verbose_name='Inches'),
        ),
    ]
