# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_auto_20161022_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_weight_ft',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_height_ft',
            field=models.IntegerField(default=5, help_text='Enter height feet', verbose_name='Your height:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_height_in',
            field=models.IntegerField(default=10, help_text='Enter height inches', verbose_name='Your height:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_weight',
            field=models.IntegerField(default=150, help_text='Enter weight in pounds', verbose_name='Your weight:'),
        ),
    ]
