# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_auto_20161023_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbmiprofile',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitness.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_height_ft',
            field=models.IntegerField(default=5, verbose_name='Your height in feet:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_height_in',
            field=models.IntegerField(default=10, verbose_name='Your height in inches:'),
        ),
    ]
