# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_auto_20161025_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(default=5)),
                ('distance', models.FloatField(default=1)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifting_cardio', models.CharField(choices=[('Lifting', 'Lifting'), ('Cardio', 'Cardio')], max_length=5)),
                ('cardio_type', models.CharField(choices=[('Running', 'Running'), ('Biking', 'Biking')], max_length=5)),
                ('muslce_group', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Abs', 'Abs'), ('Legs', 'Legs'), ('Arms', 'Arms')], max_length=5)),
            ],
        ),
    ]
