# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_workouttracker_workouttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Running', 'Running'), ('Biking', 'Biking')], max_length=5)),
                ('distance', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Abs', 'Abs'), ('Legs', 'Legs'), ('Arms', 'Arms')], max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutType',
        ),
        migrations.RemoveField(
            model_name='workouttracker',
            name='distance',
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='assisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='lift_type',
            field=models.CharField(choices=[('Bench press', 'Bench Press'), ('Chest fly', 'Chest fly'), ('Dips Machine fly', 'Dips Machine fly'), ('Push-up', 'Push-up'), ('Chin-up', 'Chin-up'), ('Pulldown', 'Pulldown'), ('Pull-up', 'Pull-up'), ('Shoulder shrug', 'Shoulder shrug'), ('Shoulder press', 'Shoulder press'), ('Biceps Curl', 'Biceps Curl'), ('Chin-up', 'Chin-up'), ('Close-grip bench press', 'Close-grip bench press'), ('Dips', 'Dips'), ('Triceps extension', 'Triceps extension'), ('Forearms', 'Forearms'), ('Crunch', 'Crunch'), ('Leg raise', 'Leg raise'), ('Russian twist', 'Russian twist'), ('Sit-up', 'Sit-up'), ('Deadlift', 'Deadlift')], default='Curls', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='sets',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workouttracker',
            name='reps',
            field=models.IntegerField(),
        ),
    ]
