# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_workouttracker_workouttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Running', 'Running'), ('Biking', 'Biking')], max_length=5)),
                ('distance', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Abs', 'Abs'), ('Legs', 'Legs'), ('Arms', 'Arms')], max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutType',
        ),
        migrations.RenameField(
            model_name='workouttracker',
            old_name='weight',
            new_name='assisted_reps',
        ),
        migrations.RemoveField(
            model_name='workouttracker',
            name='distance',
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='assisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='lift_type',
            field=models.CharField(choices=[('Bench Press', 'Bench Press'), ('Chest Fly', 'Chest Fly'), ('Dips Machine Fly', 'Dips Machine Fly'), ('Push-up', 'Push-up'), ('Chin-up', 'Chin-up'), ('Pulldown', 'Pulldown'), ('Pull-up', 'Pull-up'), ('Shoulder Shrug', 'Shoulder Shrug'), ('Shoulder Press', 'Shoulder Press'), ('Biceps Curl', 'Biceps Curl'), ('Chin-up', 'Chin-up'), ('Close-Grip Bench Press', 'Close-Grip Bench Press'), ('Dips', 'Dips'), ('Triceps Extension', 'Triceps Extension'), ('Forearms', 'Forearms'), ('Crunch', 'Crunch'), ('Leg Raise', 'Leg Raise'), ('Russian Twist', 'Russian Twist'), ('Sit-up', 'Sit-up'), ('Deadlift', 'Deadlift')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Abs', 'Abs'), ('Legs', 'Legs'), ('Arms', 'Arms')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='raw_weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouttracker',
            name='sets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workouttracker',
            name='reps',
            field=models.IntegerField(),
        ),
    ]
