# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_auto_20161027_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioworkout',
            name='exercise_type',
            field=models.CharField(choices=[('Running', 'Running'), ('Biking', 'Biking')], max_length=15),
        ),
    ]
