# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_auto_20161027_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardioworkout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workouttracker',
            name='date',
        ),
    ]
