# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_auto_20161027_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MuscleGroup',
        ),
        migrations.RemoveField(
            model_name='workouttracker',
            name='muscle_group',
        ),
    ]
