# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_workouttracker_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttracker',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitness.UserProfile'),
            preserve_default=False,
        ),
    ]
