# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0019_workouttracker_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutTracker',
            new_name='AddWorkout',
        ),
    ]
