# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0020_auto_20161029_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addworkout',
            name='lift_type',
            field=models.CharField(choices=[('Bench Press', 'Bench Press'), ('Chest Fly', 'Chest Fly'), ('Dips Machine Fly', 'Dips Machine Fly'), ('Push-up', 'Push-up'), ('Chin-up', 'Chin-up'), ('Pulldown', 'Pulldown'), ('Pull-up', 'Pull-up'), ('Shoulder Shrug', 'Shoulder Shrug'), ('Shoulder Press', 'Shoulder Press'), ('Biceps Curl', 'Biceps Curl'), ('Chin-up', 'Chin-up'), ('Close-Grip Bench Press', 'Close-Grip Bench Press'), ('Dips', 'Dips'), ('Triceps Extension', 'Triceps Extension'), ('Crunch', 'Crunch'), ('Leg Raise', 'Leg Raise'), ('Russian Twist', 'Russian Twist'), ('Sit-up', 'Sit-up'), ('Deadlift', 'Deadlift')], max_length=25),
        ),
    ]
